import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, Bell, Check, ChevronDown, ChevronUp, CircleHelp, ExternalLink, Filter, Menu, Plus, Search, Settings, SlidersHorizontal, Sparkles, TriangleAlert, X } from 'lucide-react'
import { sources } from './data'
import type { Section, Source, SourceRun, Topic } from './types'
import { addSource, loadLiveReport, loadSettings, loadSources, saveSettings, type SettingsState } from './api'

type View = 'today' | 'archive' | 'sources'

function App() {
  const [view, setView] = useState<View>('today')
  const [section, setSection] = useState<'all' | Section>('all')
  const [query, setQuery] = useState('')
  const [openTopic, setOpenTopic] = useState<string | null>('stablecoins')
  const [mobileMenu, setMobileMenu] = useState(false)
  const [showSettings, setShowSettings] = useState(false)
  const [showAddSource, setShowAddSource] = useState(false)
  const [sourceRows, setSourceRows] = useState<Source[]>(sources)
  const [settings, setSettings] = useState<SettingsState>({ reportTime: '08:00', timezone: 'Europe/London', telegramEnabled: true })
  const [liveTopics, setLiveTopics] = useState<Topic[] | null>(null)
  const [sourceRuns, setSourceRuns] = useState<SourceRun[] | null>(null)
  const [crawlStatus, setCrawlStatus] = useState('')
  useEffect(() => { loadSources().then(setSourceRows).catch(() => undefined); loadSettings().then(setSettings).catch(() => undefined); loadLiveReport().then((report) => { setLiveTopics(report.topics); setSourceRuns(report.sourceRuns); const failures = report.sourceRuns?.filter((run) => run.status !== 'ok').length ?? 0; setCrawlStatus(`Crawled ${new Date(report.generatedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} · ${report.topics.length} verified topics${failures ? ` · ${failures} sources need attention` : ''}`) }).catch(() => { setLiveTopics([]); setCrawlStatus('Live crawl not available') }) }, [])
  const reportTopics = liveTopics || []
  const leadTopic = reportTopics[0]
  const analyzedPosts = sourceRuns?.reduce((total, run) => total + run.count, 0) ?? 0
  const filteredTopics = useMemo(() => reportTopics.filter((topic) => (section === 'all' || topic.section === section) && `${topic.title} ${topic.summary} ${topic.sources.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [query, reportTopics, section])

  return <div className="app-shell">
    <header className="masthead">
      <a className="wordmark" href="#top"><span className="wordmark-mark">S</span><span>signalroom</span></a>
      <nav className={mobileMenu ? 'nav-links is-open' : 'nav-links'} aria-label="Primary navigation">
        {(['today', 'archive', 'sources'] as View[]).map((item) => <button className={view === item ? 'nav-link active' : 'nav-link'} onClick={() => { setView(item); setMobileMenu(false) }} key={item}>{item === 'today' ? 'Today' : item === 'archive' ? 'Archive' : 'Sources'}</button>)}
      </nav>
      <div className="header-actions"><button className="icon-button" aria-label="Search"><Search size={18} /></button><button className="icon-button" aria-label="Notifications"><Bell size={18} /></button><button className="settings-button" onClick={() => setShowSettings(true)}><Settings size={16} /> Settings</button><button className="mobile-menu" aria-label="Toggle navigation" onClick={() => setMobileMenu(!mobileMenu)}><Menu size={22} /></button></div>
    </header>

    {view === 'today' && <main id="top">
      <div className="topic-toolbar"><div className="section-tabs"><button className={section === 'all' ? 'tab active' : 'tab'} onClick={() => setSection('all')}>All signals <span>{reportTopics.length.toString().padStart(2, '0')}</span></button><button className={section === 'crypto' ? 'tab active crypto-tab' : 'tab crypto-tab'} onClick={() => setSection('crypto')}>Crypto <span>{reportTopics.filter((topic) => topic.section === 'crypto').length.toString().padStart(2, '0')}</span></button><button className={section === 'ai' ? 'tab active ai-tab' : 'tab ai-tab'} onClick={() => setSection('ai')}>AI <span>{reportTopics.filter((topic) => topic.section === 'ai').length.toString().padStart(2, '0')}</span></button>{crawlStatus && <span className="crawl-status">{crawlStatus}</span>}</div><div className="toolbar-right"><label className="search-field"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search signals" /></label><button className="filter-button"><Filter size={15} /> Filters</button></div></div>
      {leadTopic ? <section className="lead-story"><div className="lead-kicker"><span className={`section-chip ${leadTopic.section}`}>{leadTopic.section.toUpperCase()}</span><span>TOP SIGNAL / 01</span></div><div className="lead-grid"><h2>{leadTopic.title}</h2><div><p>{leadTopic.summary}</p><a className="text-link" href={`#${leadTopic.id}`}>Read the signal <ArrowUpRight size={16} /></a></div></div><div className="lead-footer"><span>{leadTopic.signal}</span><span>Across {leadTopic.sources.length} sources</span><span>{leadTopic.confidence}</span></div></section> : <section className="lead-story"><div className="lead-kicker"><span>LIVE REPORT</span></div><div className="lead-grid"><h2>No cross-channel topics<br /><span>in the last 24 hours.</span></h2><div><p>A topic appears only when at least two distinct configured sources discuss the same conversation.</p></div></div></section>}
      <div className="content-grid"><div className="topics-column"><div className="list-heading"><span>THE FULL READ</span><span>{filteredTopics.length} SIGNALS</span></div>{filteredTopics.length === 0 && <div className="empty-state">No cross-channel topics yet. A signal needs matching evidence from at least two distinct sources in the preceding 24 hours.</div>}{(['crypto', 'ai'] as Section[]).map((group) => { const groupTopics = filteredTopics.filter((topic) => topic.section === group); if (!groupTopics.length) return null; return <div className="topic-group" key={group}><div className={`group-heading ${group}`}><span className="group-dot" /> {group === 'crypto' ? 'Crypto conversations' : 'AI conversations'}<span className="group-line" /></div>{groupTopics.map((topic) => <TopicRow topic={topic} open={openTopic === topic.id} onToggle={() => setOpenTopic(openTopic === topic.id ? null : topic.id)} key={topic.id} />)}</div> })}</div><aside className="side-rail"><div className="rail-card change-card"><div className="rail-label">REPORT WINDOW <Sparkles size={15} /></div><h3>Only the latest 24 hours.</h3><p>Every topic is corroborated by at least two distinct configured sources. Single-source chatter is excluded.</p></div><div className="rail-card"><div className="rail-label">SOURCE PULSE <span className="pulse-live">LIVE</span></div><div className="pulse-number">{analyzedPosts.toLocaleString()}</div><p>verified posts analyzed in the last 24 hours</p><div className="rail-stat"><span>Across</span><strong>{sourceRuns?.filter((run) => run.status === 'ok').length ?? '—'} live sources</strong></div></div><div className="rail-card delivery-card"><div className="rail-label">MORNING DELIVERY</div><div className="delivery-row"><div className="delivery-icon"><Bell size={17} /></div><div><strong>Telegram report</strong><span>Next report tomorrow at 08:00</span></div><Check size={16} className="green-check" /></div><button onClick={() => setShowSettings(true)} className="rail-button">Manage delivery <ArrowUpRight size={15} /></button></div></aside></div>
    </main>}
    {view === 'archive' && <Archive />}
    {view === 'sources' && <Sources sourceRows={sourceRows} onAddSource={() => setShowAddSource(true)} />}
    {showSettings && <SettingsPanel initial={settings} onClose={() => setShowSettings(false)} onSave={(next) => { setSettings(next); saveSettings(next).catch(() => undefined) }} />}
    {showAddSource && <AddSourcePanel onClose={() => setShowAddSource(false)} onAdded={() => loadSources().then(setSourceRows).catch(() => undefined)} />}
    <footer className="footer"><span>signalroom / conversation intelligence</span><span>Private workspace · Europe/London</span></footer>
  </div>
}

function TopicRow({ topic, open, onToggle }: { topic: Topic; open: boolean; onToggle: () => void }) { return <article className={`topic-row ${open ? 'open' : ''}`} id={topic.id}><button className="topic-summary" onClick={onToggle}><span className="topic-rank">{String(topic.rank).padStart(2, '0')}</span><span className={`topic-index ${topic.section}`}>{topic.section === 'crypto' ? 'C' : 'A'}</span><span className="topic-title-wrap"><strong>{topic.title}</strong><span>{topic.summary}</span></span><span className="topic-signal">{topic.signal}</span><span className="topic-chevron">{open ? <ChevronUp size={20} /> : <ChevronDown size={20} />}</span></button>{open && <div className="evidence-panel"><div className="topic-detail"><span className="confidence">{topic.confidence}</span><span>·</span><span>{topic.sources.length} source{topic.sources.length > 1 ? 's' : ''}</span></div><div className="evidence-list">{topic.evidence.map((item) => <a href={item.url} target="_blank" rel="noreferrer" className="evidence-item" key={item.url || `${item.label}-${item.time}`}><div className="evidence-top"><span className={`source-type ${item.source.toLowerCase()}`}>{item.source}</span><span>{item.label} · {item.time}</span><ExternalLink size={13} /></div><p>“{item.excerpt}”</p><span className="evidence-author">{item.author}</span></a>)}</div></div>}</article> }
function Archive() { return <main className="subpage"><div className="eyebrow">REPORT LIBRARY / 30 DAYS</div><div className="subpage-header"><h1>Past signals.</h1><p>A growing record of what mattered, when it started, and how the conversation changed.</p></div><div className="archive-list">{['Sunday, August 23, 2026', 'Saturday, August 22, 2026', 'Friday, August 21, 2026', 'Thursday, August 20, 2026'].map((date, index) => <button className="archive-item" key={date}><span className="archive-date">{date}</span><strong>{index === 0 ? 'The quiet build-out of agent infrastructure' : index === 1 ? 'Crypto’s new center of gravity is distribution' : index === 2 ? 'When open models became the default starting point' : 'Payments, privacy, and programmable money'}</strong><span className="archive-count">{index + 4} signals <ArrowUpRight size={16} /></span></button>)}</div></main> }
function Sources({ sourceRows, onAddSource }: { sourceRows: Source[]; onAddSource: () => void }) { return <main className="subpage"><div className="eyebrow">YOUR SIGNAL MAP</div><div className="subpage-header sources-header"><div><h1>Sources.</h1><p>Control the rooms, feeds, and communities that shape your morning read.</p></div><button className="primary-button" onClick={onAddSource}><Plus size={16} /> Add source</button></div><div className="sources-list">{sourceRows.map((source) => <SourceRow source={source} key={source.id} />)}{!sourceRows.length && <div className="empty-state">No sources configured yet.</div>}</div></main> }
function SourceRow({ source }: { source: Source }) { const icon = source.kind === 'Telegram' ? 'TG' : source.kind === 'Reddit' ? 'r/' : source.kind === 'Threads' ? 'Th' : '𝕏'; return <div className="source-row"><div className={`source-avatar ${source.kind.toLowerCase()}`}>{icon}</div><div className="source-name"><strong>{source.name}</strong><span>{source.kind} · {source.detail}</span></div><span className={`source-status ${source.status.toLowerCase().replace(' ', '-')}`}>{source.status === 'Connected' ? <Check size={13} /> : <TriangleAlert size={13} />}{source.status}</span><span className="source-count">{source.count}</span><button className="icon-button"><SlidersHorizontal size={17} /></button></div> }
 function SettingsPanel({ initial, onClose, onSave }: { initial: SettingsState; onClose: () => void; onSave: (settings: SettingsState) => void }) { const [draft, setDraft] = useState(initial); return <div className="modal-backdrop" onClick={onClose}><section className="settings-panel" onClick={(event) => event.stopPropagation()}><div className="settings-head"><div><div className="eyebrow">WORKSPACE SETTINGS</div><h2>Make the signal yours.</h2></div><button className="icon-button" onClick={onClose} aria-label="Close settings"><X size={20} /></button></div><div className="settings-section"><h3>Report schedule</h3><div className="setting-row"><div><strong>Daily report time</strong><span>Your local morning briefing</span></div><input aria-label="Daily report time" type="time" value={draft.reportTime} onChange={(event) => setDraft({ ...draft, reportTime: event.target.value })} /></div><div className="setting-row"><div><strong>Timezone</strong><span>Used to calculate the report window</span></div><select aria-label="Timezone" value={draft.timezone} onChange={(event) => setDraft({ ...draft, timezone: event.target.value })}><option>Europe/London</option><option>Asia/Taipei</option><option>Asia/Seoul</option><option>UTC</option></select></div></div><div className="settings-section"><h3>Delivery</h3><div className="setting-row"><div><strong>Telegram delivery</strong><span>Send the full report to your private channel</span></div><button aria-label="Toggle Telegram delivery" className={draft.telegramEnabled ? 'toggle on' : 'toggle'} onClick={() => setDraft({ ...draft, telegramEnabled: !draft.telegramEnabled })}><span /></button></div></div><div className="settings-section"><h3>AI summaries</h3><div className="setting-row"><div><strong>Summary style</strong><span>Compact editorial read with evidence</span></div><span className="setting-value">Editorial</span></div></div><div className="settings-note"><CircleHelp size={16} /><span>Live source connections are configured with environment secrets and never displayed here.</span></div><button className="save-button" onClick={() => { onSave(draft); onClose() }}>Save settings</button></section></div> }

function AddSourcePanel({ onClose, onAdded }: { onClose: () => void; onAdded: () => void }) { const [kind, setKind] = useState<'Telegram' | 'Reddit' | 'X' | 'Threads'>('Telegram'); const [name, setName] = useState(''); const [detail, setDetail] = useState(''); const [section, setSection] = useState<'crypto' | 'ai'>('crypto'); const [status, setStatus] = useState(''); const submit = async () => { if (!name.trim()) { setStatus('Name is required'); return } try { await addSource({ kind, name: name.trim(), detail: detail.trim(), section, config: kind === 'Reddit' ? { subreddit: detail.replace(/^r\//, '') } : kind === 'X' ? { query: detail } : kind === 'Telegram' ? { chatId: detail } : {} }); onAdded(); onClose() } catch { setStatus('Start the full-stack server to save sources.') } }; return <div className="modal-backdrop" onClick={onClose}><section className="settings-panel" onClick={(event) => event.stopPropagation()}><div className="settings-head"><div><div className="eyebrow">NEW SOURCE</div><h2>Add a room.</h2></div><button className="icon-button" onClick={onClose} aria-label="Close source setup"><X size={20} /></button></div><div className="source-form"><label>Platform<select value={kind} onChange={(event) => { const next = event.target.value as typeof kind; setKind(next); setSection(next === 'Telegram' ? 'crypto' : 'ai') }}><option>Telegram</option><option>Reddit</option><option>X</option><option>Threads</option></select></label><label>Name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. The Defiant" /></label><label>{kind === 'Reddit' ? 'Subreddit' : kind === 'X' ? 'Search query' : kind === 'Telegram' ? 'Channel username or chat ID' : 'Threads user ID'}<input value={detail} onChange={(event) => setDetail(event.target.value)} placeholder={kind === 'Reddit' ? 'LocalLLaMA' : kind === 'X' ? '(agents OR inference) lang:en' : kind === 'Telegram' ? '@channel' : '123456789'} /></label><label>Report section<select value={section} onChange={(event) => setSection(event.target.value as 'crypto' | 'ai')}><option value="crypto">Crypto</option><option value="ai">AI</option></select></label>{status && <p className="form-status">{status}</p>}<button className="save-button" onClick={submit}>Add source</button></div></section></div> }

export default App
