import type { Source, Topic } from './types'

export const topics: Topic[] = [
  { id: 'stablecoins', rank: 1, section: 'crypto', title: 'Stablecoins are becoming the default settlement layer', summary: 'Conversation has shifted from whether stablecoins matter to where they quietly replace existing payment rails: treasury, payroll, and cross-border settlement are the strongest threads.', signal: '↑ 42% conversation volume', sources: ['@JeJeCryptoDiary', '@cryptocurrencymage', '@pgyinfo'], confidence: 'High confidence', evidence: [{ source: 'Telegram', label: '@JeJeCryptoDiary', author: '@JeJeCryptoDiary', excerpt: 'The most interesting stablecoin story is increasingly happening outside of exchanges.', time: '42m ago', url: 'https://t.me/' }, { source: 'Telegram', label: '@cryptocurrencymage', author: '@cryptocurrencymage', excerpt: 'Payments teams are now treating stablecoin rails as infrastructure, not an experiment.', time: '1h ago', url: 'https://t.me/' }] },
  { id: 'restaking', rank: 2, section: 'crypto', title: 'The restaking reset is separating utility from leverage', summary: 'Builders are revisiting the promise of shared security with a more skeptical lens. The dominant question is what creates durable demand once incentives disappear.', signal: '29 channels discussing', sources: ['@pgyinfo', '@justdegenguy', '@mujammin123'], confidence: 'Mixed signal', evidence: [{ source: 'Telegram', label: '@pgyinfo', author: '@pgyinfo', excerpt: 'Restaking is finding a more precise vocabulary around what is actually secured.', time: '2h ago', url: 'https://t.me/' }] },
  { id: 'consumer-crypto', rank: 3, section: 'crypto', title: 'Consumer crypto is looking for a better reason to come back', summary: 'The mood is moving beyond launch-day novelty. Wallet UX, social coordination, and payments are being discussed as retention loops rather than acquisition moments.', signal: '↑ 18% cross-source overlap', sources: ['@justdegenguy', '@mujammin123', '@JeJeCryptoDiary'], confidence: 'Early signal', evidence: [{ source: 'Telegram', label: '@mujammin123', author: '@mujammin123', excerpt: 'Distribution is not the same thing as retention. The next consumer winners will prove the loop.', time: '3h ago', url: 'https://t.me/' }] },
  { id: 'agents', rank: 1, section: 'ai', title: 'Agents are moving from demos into the operating layer', summary: 'AI discussion is clustering around agents that own a workflow end-to-end: permissions, memory, evaluation, and the unglamorous handoffs between tools.', signal: '↑ 67% conversation volume', sources: ['r/LocalLLaMA', 'Threads / founders'], confidence: 'High confidence', evidence: [{ source: 'Reddit', label: 'r/LocalLLaMA', author: 'u/latent_builder', excerpt: 'The interesting benchmark is no longer “can it call a tool?” but “can it recover when the tool fails?”', time: '18m ago', url: 'https://reddit.com/' }, { source: 'Threads', label: 'Threads / founders', author: '@productsystems', excerpt: 'The agent stack is becoming an operations problem, which is a good sign.', time: '1h ago', url: 'https://threads.net/' }] },
  { id: 'open-models', rank: 2, section: 'ai', title: 'Open models are winning the iteration-speed argument', summary: 'Developers are trading a little frontier performance for control, lower latency, and the ability to shape models around their own evaluation sets.', signal: '14,820 posts in 24h', sources: ['r/MachineLearning', 'Hugging Face', 'X / research'], confidence: 'High confidence', evidence: [{ source: 'Reddit', label: 'r/MachineLearning', author: 'u/model_context', excerpt: 'The gap that matters is not leaderboard points; it is how quickly a team can close its own gap.', time: '2h ago', url: 'https://reddit.com/' }] },
  { id: 'ai-infra', rank: 3, section: 'ai', title: 'Inference economics are back in the product conversation', summary: 'Teams are talking less about model access in isolation and more about the cost curve: routing, caching, smaller specialists, and the moment a feature earns its GPU bill.', signal: '↑ 31% on yesterday', sources: ['Latent Space', 'r/MLQuestions', 'Threads / founders'], confidence: 'Mixed signal', evidence: [{ source: 'Threads', label: 'Threads / founders', author: '@productsystems', excerpt: 'Every AI product now has a second roadmap: make the model cheaper to use.', time: '4h ago', url: 'https://threads.net/' }] },
]

export const sources: Source[] = [
  { id: 'jeje-crypto-diary', kind: 'Telegram', name: 'JeJe Crypto Diary', detail: '@JeJeCryptoDiary', status: 'Connected', count: 'Ready to crawl' },
  { id: 'cryptocurrency-mage', kind: 'Telegram', name: 'Cryptocurrency Mage', detail: '@cryptocurrencymage', status: 'Connected', count: 'Ready to crawl' },
  { id: 'pgyinfo', kind: 'Telegram', name: 'PGY Info', detail: '@pgyinfo', status: 'Connected', count: 'Ready to crawl' },
  { id: 'just-degen-guy', kind: 'Telegram', name: 'Just Degen Guy', detail: '@justdegenguy', status: 'Connected', count: 'Ready to crawl' },
  { id: 'mujammin123', kind: 'Telegram', name: 'Mujammin123', detail: '@mujammin123', status: 'Connected', count: 'Ready to crawl' },
  { id: 'llama', kind: 'Reddit', name: 'r/LocalLLaMA', detail: 'configured community', status: 'Connected', count: '4,821 posts' },
  { id: 'threads-founders', kind: 'Threads', name: 'Founder signals', detail: 'configured list', status: 'Needs setup', count: 'Connect account' },
]

export const reportDate = 'Monday, August 24, 2026'
